[project]
name = "dbt-modern-data-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.3",
    "dbt-core>=1.10.1",
    "dbt-postgres>=1.9.0",
    "psycopg>=3.2.9",
]
