WITH source AS (
  SELECT * FROM {{ source('fivetran_facebook', 'account_history') }}
),

final AS (
  SELECT
    id AS account_id,
    age,
    amount_spent,
    balance,
    business_city,
    business_country_code,
    business_name,
    business_state,
    business_street,
    business_street_2,
    business_zip,
    can_create_brand_lift_study,
    created_time,
    currency,
    end_advertiser,
    end_advertiser_name,
    funding_source,
    has_migrated_permissions,
    io_number,
    is_attribution_spec_system_default,
    is_direct_deals_enabled,
    is_in_3_ds_authorization_enabled_market,
    is_notifications_enabled,
    is_personal,
    is_prepay_account,
    is_tax_id_required,
    media_agency,
    min_campaign_group_spend_cap,
    min_daily_budget,
    "name" AS account_name,
    next_bill_date,
    offsite_pixels_tos_accepted,
    "owner",
    partner,
    salesforce_invoice_group_id,
    spend_cap,
    tax_id,
    tax_id_type,
    timezone_id,
    timezone_name,
    timezone_offset_hours_utc,
    account_status,
    disable_reason,
    tax_id_status,
    agency_client_declaration_agency_representing_client,
    agency_client_declaration_client_based_in_france,
    agency_client_declaration_client_city,
    agency_client_declaration_client_country_code,
    agency_client_declaration_client_email_address,
    agency_client_declaration_client_name,
    agency_client_declaration_client_postal_code,
    agency_client_declaration_client_province,
    agency_client_declaration_client_street,
    agency_client_declaration_client_street_2,
    agency_client_declaration_has_written_mandate_from_advertiser,
    agency_client_declaration_is_client_paying_invoices,
    business_manager_block_offline_analytics,
    business_manager_created_by,
    business_manager_created_time,
    business_manager_extended_updated_time,
    business_manager_is_hidden,
    business_manager_link,
    business_manager_name,
    business_manager_payment_account_id,
    business_manager_primary_page,
    business_manager_profile_picture_uri,
    business_manager_timezone_id,
    business_manager_two_factor_type,
    business_manager_updated_by,
    business_manager_update_time,
    business_manager_verification_status,
    business_manager_vertical,
    business_manager_vertical_id,
    business_manager_manager_id,
    extended_credit_invoice_group_id,
    extended_credit_invoice_group_auto_enroll,
    extended_credit_invoice_group_customer_po_number,
    extended_credit_invoice_group_email,
    extended_credit_invoice_group_emails,
    extended_credit_invoice_group_name,
    funding_source_details_id,
    funding_source_details_coupon,
    funding_source_details_coupons,
    funding_source_details_coupon_id,
    funding_source_details_amount,
    funding_source_details_currency,
    funding_source_details_display_amount,
    funding_source_details_expiration,
    funding_source_details_display_string,
    funding_source_details_campaign_ids,
    funding_source_details_original_amount,
    funding_source_details_original_display_amount,
    funding_source_details_type,
    capabilities,
    ROW_NUMBER() OVER (
      PARTITION BY id
      ORDER BY age DESC
    ) = 1 AS is_latest_value,
    "_fivetran_id",
    "_fivetran_synced"
  FROM source
)

SELECT * FROM final
